### ISSUE TITLE
SharedParameter.Create in Revit 2023

### ISSUE THREAD

**Issue by Hoss1831** [erfajo/OrchidForDynamo#254] opened 2024-08-01 10:45 UTC
### Revit, Dynamo and Orchid version

Revit: 2023.1 23.1.40.56
Dynamo: 2.16.3.11903
Orchid: 2.16.6.6309

### The issue
Hello,
I have been using this node to export sharred parameters from revit familieis (mainly Title Blocks) and it works perfectly fine in revit 2021 and below. I have tried few things and can't get this to work in revit 2023.
Is there a issue with this node? could you please share a sample fife on how to use it? thanks 

![image](https://github.com/user-attachments/assets/d7156174-ac6c-442b-9e89-c0c443227b8d)

**Comment by erfajo** [comment] 2024-08-02 16:07
I was made aware, that there was an error in that build (and the subsequent until the 6323 build) by other users with the parameter nodes. These errors should be fixed in the 6324 build (and beyond), please download the latest build and please confirm if the problem is solved :-)

**Comment by Hoss1831** [comment] 2024-08-05 14:59
It could be the method I use. I have tried few ways to extarct groupname, spectype and group type from the existing shared parameter whic I want to export, and although I am not getting any errors, nothing gets exported

**Comment by erfajo** [comment] 2024-08-06 06:25
Sounds like you have more than one error... please add .txt to your graph file, then you can upload it here... and if other files are needed then upload a zip file. Remember to keep files as small as possible.

**Comment by Hoss1831** [comment] 2024-08-07 15:44
thanks for your reply, I think the error is with how I extrat some of the values from existing shared parameter within the family.
I need to find the right node or write a python script to sort this issue. Thanks again for your help

**Comment by erfajo** [comment] 2024-08-08 05:53
I will then close this issue.

**Closed by erfajo** 2024-08-08 05:53 UTC
