### ISSUE TITLE
Reorder Family Parameters

### ISSUE THREAD

**Issue by HVCFOGEY34** [erfajo/OrchidForDynamo#143] opened 2022-01-04 20:52 UTC
### Is your feature request related to a problem? Please describe.

The issue I'm running into right now is I want to add parameters to a bunch of families, and I can easily add them, but then the new parameters order in the list is not how I would like it. I see there is functionality in the Revit API to control the parameter order with the [ReorderParameters](https://www.revitapidocs.com/2022/f3e5375b-28d7-d6c6-ea49-bf6f6289fd9a.htm) method.

### Describe the solution you'd like 

I would like to have a node that can use this functionality to reorder family parameters (not necessarily just for new parameters).

### Describe alternatives you've considered 

I tried to make a python script to do it, and I got it to work the way I wanted it, but I don't understand enough of everything to get it working outside of the current family document I have open. When I try to use the Python script I have now in a project environment that opens families in the project to edit, it doesn't seem to "commit" the changes. It doesn't have any errors, it just doesn't seem to sort the parameters.

Screenshot of my graph:
![Image](https://user-images.githubusercontent.com/6226581/148122349-da51940f-09fe-48d8-9560-e1858f980713.png)

My python code below. Inputs are:
IN[0] = Family document(s) (Not orchid. Used rhythm "Documents.OrchidDocumentToDbDocument" node to convert)
IN[1] = Parameters to move
IN[2] = Parameters to insert moved parameters under

### Additional context 

The basic idea for my use case is to feed the node the new parameters and the parameters they should appear under (both lists need to be same length) and the family document that the parameters belong to, and it would sort them. Then I would load the family back in the project and close the file. I'm sure my code is not the cleanest or most efficient, so let me know if you need any clarification. 

Thanks!

**Comment by HVCFOG3Y34** [comment] 2022-01-04 21:15
As a side issue; I keep getting a warning on the Parameter.Associate node the first time I run the graph saying "Parameter.Associate operation failed. A sub-transaction can only be active inside an open transaction" and it wont associate the parameters. I have to recreate the node and run the graph again before loading the families back into the project.

**Comment by HVCFOG3Y34** [comment] 2022-01-05 20:34
So I think I figured out why my python script wont work. The rhythm node seems to be outputting the same family document over and over and ignoring the rest of the family docs in the list. After a lot of messing around, I figured out a work around that works for me.

Image of graph:
IN[0] = Orchid Documents
![image](https://user-images.githubusercontent.com/6226581/148284917-6cdb0949-7dc8-400e-95dd-db9d014819ba.png)

My python scripts from left to right:

"Converts" Orchid documents to Revit DB:
(Gets all open documents, subtracts current project file, and sorts to match the orchid documents order)
```
# Load the Python Standard and DesignScript Libraries
import sys
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# The inputs to this node will be stored as a list in the IN variables.
orchidDocs = IN[0]
out = []


# Place your code below this line
def getOpenDocs():
    doc = DocumentManager.Instance.CurrentDBDocument
    documents = []
    uiApp = DocumentManager.Instance.CurrentUIApplication
    app = uiApp.Application
    
    for d in app.Documents:
        if d.Title == doc.Title:
            continue
        try:
            documents.append(d)
        except:
            None
    return(documents)

# Make text list of Revit docs
documents = getOpenDocs()
docsStr = []
for document in documents:
    docsStr.append(document.Title)

# Convert orchid docs to text
for x,orchid in enumerate(orchidDocs):
    orchidDocs[x] = orchid.ToString().replace("Family Document : ","")

# Put Revit documents in same order as orchid docs
for orchidDoc in orchidDocs:
    x = docsStr.index(orchidDoc)
    out.append(documents[x])        

# Assign your output to the OUT variable.
OUT = out
```

Reorder family parameters:
(Nothing changed since last post)
```
# Load the Python Standard and DesignScript Libraries
import sys
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
from Autodesk.Revit.DB import *

clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference('RevitServices')
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

import copy

# The inputs to this node will be stored as a list in the IN variables.
docs = IN[0]
newParameters = IN[1]
insertAfter = IN[2]
out = []

# Ensure in list
if type(docs) != list:
    docs = [docs]

# Place your code below this line
for doc in docs:
    uiapp = DocumentManager.Instance.CurrentUIApplication
    familyDoc = doc
    familyParams = familyDoc.FamilyManager.GetParameters()
    familyManager = familyDoc.FamilyManager
    types = familyDoc.FamilyManager.Types
    familyMannager = familyDoc.FamilyManager
    
    # Convert parameters to strings
    for x,parameter in enumerate(familyParams):
        familyParams[x] = familyParams[x].Definition.Name

    # Remove new parameters in list to insert in the correct location later.
    for newParemter in newParameters:
        familyParams.remove(newParemter)
    
    # Insert new parameters in parameters list
    for newParameter,insert in zip(newParameters,insertAfter):       
        index = familyParams.index(insert) + 1
        familyParams.insert(index,newParameter)
    
    # Convert parameters back to parameter
    for x,parameter in enumerate(familyParams):
        familyParams[x] = familyDoc.FamilyManager.get_Parameter(familyParams[x])
        
    # Sort Parameters    
    TransactionManager.Instance.EnsureInTransaction(familyDoc)
    familyManager.ReorderParameters(familyParams)
#    TransactionManager.Instance.TransactionTaskDone() 
    TransactionManager.Instance.ForceCloseTransaction()
    out.append(doc.Title)

# Assign your output to the OUT variable.
OUT = out
```

I also figured out my issue with the Parameter.Associate node. I read in another post to place a Transaction.End node before the inputs so I did that and it worked. I guess another nodes transaction was still open causing problems?

**Comment by erfajo** [comment] 2022-01-06 09:18
Could you upload the graph file?
-add ".txt" as a new extension, and then attach it. By doing that you would attach the python part as well.

Hereafter I will try to traverse what you are asking for.

Could I ask you to remove the python part from the issue, since that is blurring the overview of the issue :-)

**Comment by HVCFOG3Y34** [comment] 2022-01-06 14:18
Sure.
[Reorder Parameters.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/7822222/Reorder.Parameters.dyn.txt)

I simplified the graph to remove the unnecessary nodes just to focus on the parameter sorting part. I also made a custom node for the reorder parameters part so I copied out the contents in an orange node group.

Here is how I imagined the node:
![image](https://user-images.githubusercontent.com/6226581/148396635-1fe751bd-e6ac-4267-bcc8-2b1e6467a077.png)

**Comment by erfajo** [comment] 2022-01-06 15:27
Just by looking at what you suggest would I belive that what you are searching for, is "Parameter.Rename", since you are capturing all parameter content in memory and send it it back to newly created parameters... that would I see as a waste of computational time if you could just rename the parameter!?
![Reorder Parameters_erfajo](https://user-images.githubusercontent.com/2844374/148406737-62d4542c-adee-4e5e-a2f7-5e5a5c99746f.png)
[Reorder.Parameters_erfajo.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/7822840/Reorder.Parameters_erfajo.dyn.txt)

Besides, I have removed all other nodes than dynamoteam nodes and orchid nodes... there is no reason for other packages :-)

**Comment by erfajo** [comment] 2022-01-06 15:40
Just a second thought, why renaming at all? Why don’t you just create the parameters with the proper name from the beginning?
![Reorder Parameters2_erfajo](https://user-images.githubusercontent.com/2844374/148408780-354da59a-cd99-414a-a64f-1b0a45fbd739.png)
[Reorder.Parameters2_erfajo.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/7822934/Reorder.Parameters2_erfajo.dyn.txt)

**Comment by HVCFOG3Y34** [comment] 2022-01-06 18:59
I'm a little confused on what you are talking about. 

I don't want to rename the parameters. If you are referring to the original graph I posted, I wanted to rename a few parameters because I'm working on existing families and things changed, so I just needed to rename a few, but that's not really related to the issue. 

I also needed to add a few new parameters which I did name correctly from the beginning. The issue is I have a custom order to the parameters (not alphabetical) that I want to insert the newly created parameters in a certain order in the parameters list. If I just create the parameters without messing with the order, they will get inserted at incorrect locations in the properties parameters list.

I'm not sure what you mean by "capturing all parameter content in memory and send it back to newly created parameters...". Are you referring to the python node? It captures all the parameters because the ReorderParameters method requires all the parameters in the order you want them to work.

**Comment by HVCFOG3Y34** [comment] 2022-01-06 19:09
> Besides, I have removed all other nodes...

Thanks. I only used the other nodes because I already have them installed for other graphs and they were just the first nodes I found when searching.

**Comment by erfajo** [comment] 2022-01-07 06:25
Ok, now I get it. However, as I understand it, you are essentially trying to fix something not broken. This is not recommendable, you should pay close attention to “if it ain't broken don’t fix it”. This means also that I cant see the need for the node you are asking for. If I made such a node would I also be fixing something not broken.

I am convinced that it is more in the ball game of pure luck if you will succeed in ordering your parameters by creating them in a certain order, I would not expect this to work for sure!

I believe that you by the present nodes in my package could achieve what you are asking for. You need to get the parameter values into memory, then delete all parameters, then create all parameters again in the order you think will be shown as you wish it, then add parameter values by parameter name again.

**Comment by HVCFOG3Y34** [comment] 2022-01-07 14:51
Nice! Thanks for looking into this!

Its not working for me though. The reorder node keeps returning false and not reordering the parameters.
FYI for the graph; I had to switch the Selection.ElementByCategory back to the rhythm SelectElementsInOrder node because I only want to select a few families from my project and not all of a certain category. 
![image](https://user-images.githubusercontent.com/6226581/148558706-93082c19-0fce-4f9e-8f3e-96ad094430e0.png)
[Reorder.Parameters3_.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/7829374/Reorder.Parameters3_.dyn.txt)

The node doesn't function like how I was expecting it to be, but I guess it makes sense since it will allow more control in the long run. For my current use though, a few other nodes and a python node will always have to accompany the reorder node to accomplish what I want.

Could I suggest the reorder node accept strings for the parameters instead of a parameter element? It would follow how the rest of the parameter nodes work, and at least for me, it would make organizing the parameters a little bit easier. Otherwise, I have to convert the parameters to strings to reorder them, and then convert back just for the node.

Thanks!

**Comment by erfajo** [comment] 2022-01-07 15:28
You should not add any python to that... just a ordered list of strings (parameters)... nothing else! Try to see what a did in the red box in my graph... do only do what that showed!
however, if I am going to help you testing, you need to upload a bare minimum of a sample file... remember to rename the file (add .txt extension)

**Comment by HVCFOG3Y34** [comment] 2022-01-07 17:43
I did add my file below the picture in my last post. 

I think there is some confusion again. I'm running this graph in a project environment with families I selected from it and opened for editing. In this test example I selected two families from the project to edit.

The way you use the list.join node would cause an error because it would be duplicating parameters. Its getting all the parameters in the family (which include the newly created parameters) and adding the new parameters again, and adding parameters that already existed in the family again.

The python node I had is important because it's sorting the parameters in the way I want them. Its taking in all the parameters of each family (IN[0]), removing the newly created parameters (IN[1]) from each the list (to reinsert later in the appropriate location), then reinserting them after a specified parameter (IN[2]). So what's coming out of the python node is one list of ordered parameters for each family. In this test case, I'm working with two family documents, so I had two ordered lists of parameters (one list of parameters for each family going in the Parameter.Reorder node). 

Even If I only work on one family and flatten the lists of parameters, it still only outputs false. It wasn't until after I used my python node to sort the parameters that your Parmaeter.Reorder node output true.

New graph attached:
[Reorder.Parameters4.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/7830415/Reorder.Parameters4.dyn.txt)

**Comment by erfajo** [comment] 2022-01-07 17:46
I need the revit file... since it is families it would be an rfa file

**Comment by HVCFOG3Y34** [comment] 2022-01-07 19:19
Apologies. Though you could use any project file with families in it for this scenario. I have proprietary elements in my actual file, so I used one of Revits sample files and recreated the scenario.
[Sample.rvt.txt](https://github.com/erfajo/OrchidForDynamo/files/7830841/Sample.rvt.txt)
Dynamo graph to with project: 
[Reorder.Parameters5.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/7830843/Reorder.Parameters5.dyn.txt)

**Comment by erfajo** [comment] 2022-01-09 13:51
As always I should remember to start with the base case, for doing a node. I have done that now, and then it was easy to make the node. I took the family I needed for the job, and made the node without adding any other parameters, I just reordered some og you existing parameters, and that worked... So it should also work for you case, however, I have not seen into you graph, since you send me a graph containg a node I dont want to add to my environment, however, I think you will manage.

please download the newly uploaded beta!
![Reorder Parameters](https://user-images.githubusercontent.com/2844374/148684921-b121224b-040d-4957-b89f-1bd012b1e663.png)
[Reorder.Parameters.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/7835171/Reorder.Parameters.dyn.txt)

**Comment by HVCFOGEY34** [comment] 2022-01-10 14:00
It works on one family now, but if you run it on multiple, every family except the first return false and doesn't order. Also, I'm running into the issue of keeping the parameters in the existing order they were in because the Document.Parameters node returns all the parameters sorted in alphabetical order and doesn't preserve the original order (maybe a bool input to preserve original order with null being alphabetical?).

Here are my files. I replaced the element selection node to an Orchid one, so the whole graph only uses Orchid or OOTB nodes. 
[Reorder.Parameters5.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/7839294/Reorder.Parameters5.dyn.txt)
[Sample.rvt.txt](https://github.com/erfajo/OrchidForDynamo/files/7839295/Sample.rvt.txt)

**Comment by erfajo** [comment] 2022-01-10 14:51
arhhh... I am affraid I know exactly whats wrong :-S
I am sure it is a transaction issue.
I will return to you later when I have the time for testing it...

**Comment by erfajo** [comment] 2022-01-11 08:20
It was the well-known transaction issue... I just forgot, when you give the user an option for using your nodes with background-loaded documents, then must each document be closed in transaction. However, I have tried this time to make a function that tests if it is the case that several documents are using the node, and if so, then force-close transaction, if not then just close transaction.
I did test it on your base-case and it worked for me, so hopefully does it also work for you.
In my test, I could also verify that your python part did not sort your parameters correct (due to your naming of the test parameters), however, my reordering made the order you send to the node :-)
I have now uploaded my next version since I also finished all my tests and updated all my sample files!

**Comment by HVCFOGEY34** [comment] 2022-01-11 18:39
I just downloaded and can confirm the reorder node is working. Thank you so much!

Yeah, the order of the parameters is now how I would like them (as you saw with the test parameters naming), but that's because the Document.Parameters node doesn't return the existing order of the parameters, and instead sorts them alphabetically. So for my use case to work, that node would need an option to output the parameters in the existing order and not sort them alphabetically.

I don't know if you made the node to sort them, or if whatever API call you're using sorts them, but if its the [SortParameters method](https://www.revitapidocs.com/2022/86e30f63-4894-aed9-c6df-0074cdfa89a7.htm) (by default, it outputs them in the existing order), it would be nice to have a bool input option to alphabetically sort or not (with the default value being alphabetically sort).

**Comment by erfajo** [comment] 2022-01-11 19:01
I am not sorting any parameters, this is what I have left for the user to decide, that is the most robust way to do would I presume :-)

If you want to sort anything, then I have two sort nodes, try it out :-)

I will now close the issue :-)

**Closed by erfajo** 2022-01-11 19:01 UTC
Labels: enhancement, solved

**Comment by HVCFOGEY34** [comment] 2022-01-11 19:21
The Document.Parameters node sorts the parameters it retrieves. For my use case, I cannot use this node and currently would have to make my own solution using the [SortParameters method](https://www.revitapidocs.com/2022/86e30f63-4894-aed9-c6df-0074cdfa89a7.htm) to retrieve my parameters.
![image](https://user-images.githubusercontent.com/6226581/149006892-88749b18-2eb7-49ab-88e0-cd16a8f81bf7.png)

**Comment by erfajo** [comment] 2022-01-11 19:47
Thats correct, The element.Parameters from the dynamo team does also that... however, that is not written in stone. I could change that... I think this is choosen since it makes it easier to find a parameter in the output by mouse over.
If I have had this info could I have added this to the newly release... I have not planned to release anything within the next two weeks :-S
How critical is it for you?

**Comment by HVCFOGEY34** [comment] 2022-01-11 23:32
Hvcfog3y34@gmail.com
Only 212 is fine.
Thank you so much!

**Comment by erfajo** [comment] 2022-01-12 04:48
I have shared a online beta build folder with you, please report if you cant get the content...
I also deleted your message containing your mail address so you dont get spam :-)

**Comment by HVCFOGEY34** [comment] 2022-01-12 13:33
I received it. I tried to install it, but couldn't get it working in Dynamo. I don't know where the .exe installed the package files. When I tried to run the exe the first time without administrator privileges, it said it couldn't create a folder in C:\Windows\System32\%BuildtInPackages%. After I ran it as administrator, it finished installing, but I didn't see a folder in that location.

Don't worry about fixing this for me. I can use a work around to get what I need for now. I can wait until the next release whenever that is.

Thank you so much for implementing the reorder node and trying to get the beta to me.

**Comment by erfajo** [comment] 2022-01-12 14:14
normally would it be here
C:\Users\ xxx \AppData\Roaming\Dynamo\Dynamo Revit\2.12\packages\Orchid

I can give you the files as a zip file, where you manually place them in the corret folder

**Comment by HVCFOGEY34** [comment] 2022-01-12 14:51
I checked there and a few other places and didn't see it.

If its easy enough to send, sure. Otherwise, its fine.

**Comment by erfajo** [comment] 2022-01-12 15:15
I have placed the zipfiles in the folder, including the daily build

**Comment by HVCFOGEY34** [comment] 2022-01-12 15:22
This works for me! Thanks!

**Comment by erfajo** [comment] 2022-01-13 09:46
...and everything worked?... I tried to implement my new transaction feature in all “family” nodes and some selected other nodes…
Could I ask you to test for me by installing the new beta I have put in the folder? I have taken a large portion of functions where I have updated the transaction method. It would be nice for me to have you test it for me for a while before I release it the next time :-)
I am also testing it myself :-)

**Comment by HVCFOGEY34** [comment] 2022-01-13 14:39
Sure. Give me some time to test and I'll get back to you with how it goes.

**Comment by HVCFOGEY34** [comment] 2022-01-14 18:36
It looks like I wont be able to test things for you this week. I have a project I'm going to be working on where I'll be able to play with some of the nodes, but I probably wont be getting to it until sometime next week.

**Comment by erfajo** [comment] 2022-01-15 09:28
right... I will delete the folder I have shared with you
