### ISSUE TITLE
o|Document.BackgroundOpen output bug

### ISSUE THREAD

**Issue by Lazarica-t** [erfajo/OrchidForDynamo#149] opened 2022-04-14 10:43 UTC
### Operating system
Windows 10

### Revit and Dynamo version
Revit: 2020.2.7
Dynamo: 2.3.1
Orchid: 203.3.0.8138

### What did you do? 
I'm trying to open .rfa files in the background to add some shared parameters

### What did you expect to see?
The **o|Document.BackgroundOpen** node to display the list of files that are being opened

### What did you see instead?
The **o|Document.BackgroundOpen** node does not display correct information, it's displaying null even thought when I hover over the node it says it's output is a list.. 

The last stable/working version seems to be 230.0.0.7283 :(
![image](https://user-images.githubusercontent.com/49474519/163594567-45bf81af-bc32-484f-acb9-8163a0bab9c5.png)

![image](https://user-images.githubusercontent.com/49474519/163372219-b07b7876-e527-493f-86bf-d234af484387.png)
![image](https://user-images.githubusercontent.com/49474519/163372342-b0813d20-4017-40d4-9e83-9e4ce0dbe8c0.png)

Update to my original post:

When back to check the sample files, to see if anything changed in the workflows maybe. 
I used one of your graphs **Document.dyn** and ran the script and it seems to work, it detects the background files.
But if I try to recreate the graph from start, using the exact same nodes it just doesn't work! How is that even possible? This is very confusing. Now it looks to me that the **Document.Opened** node doesn't always work.
![image](https://user-images.githubusercontent.com/49474519/163578579-8f0bc584-562d-47e7-af21-37bce645dccf.png)
![image](https://user-images.githubusercontent.com/49474519/163578603-789d3c80-0413-4e12-ac95-ca25a93b4ff1.png)

**Comment by erfajo** [comment] 2022-04-15 14:06
I simply cant reproduce your error... 
![image](https://user-images.githubusercontent.com/2844374/163580560-afe6c5c3-6c10-4bbc-8e16-4827ae193bbe.png)

can I have your graph? and what else do you have installed of packages?

**Comment by Lazarica-t** [comment] 2022-04-15 21:14
Sure, this the graphs I used for testing. 
[Home-Add_parameter.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/8498251/Home-Add_parameter.dyn.txt)

Some snapshots with comments:
![image](https://user-images.githubusercontent.com/49474519/163632471-0574ab7e-5080-465d-a5ac-ddd4bc5e4e64.png)
![image](https://user-images.githubusercontent.com/49474519/163632477-a69ba9a7-8091-4bce-8367-12d3481f3110.png)


I have removed all other packages and disabled all Revit add-ons just to be sure, but no luck.
I have no idea what else could be interfering ..

**Comment by erfajo** [comment] 2022-04-17 09:25
I can't replicate your error...
Please try to delete the entire package from your storage path. Then reinstall the package or try manually to unzip the "Revit" package (zipped version).
If this still fails, then try to remove all other packages and then test it once more. I am affraid that it could be another package which is the problem.
![image](https://user-images.githubusercontent.com/2844374/163708528-afaa6774-ca92-4822-8d02-0a446daa54e1.png)

**Comment by erfajo** [comment] 2022-04-17 09:28
By the way, you are closing the documents later in this graph, this means that you will not be able to see them if that node is active!

**Comment by Lazarica-t** [comment] 2022-04-17 19:06
Well it used to work with the **Document.Close** being active (at least with version 7283 it does) , that is why it's a bit confusing for me. Is it not required to close the documents? :D
Indeed if i remove the **Document.Close** from the equation the graph works.

But, shouldn't I want to close the documents that are opened in the background? If I run the script multiple times (in Dynamo Player) won't a bunch of files remain opened in the background (and fill up the memory)?

**Comment by erfajo** [comment] 2022-04-18 09:55
If you could see any documents before is it just showing that you had a slower computer or something like that. It is one of those errors that should not occur. However, it demonstrates why we are working with graphs (DAG: https://en.wikipedia.org/wiki/Directed_acyclic_graph), and that a slang phrase as “script” should never be used… The issue you have triggered is “the closing problem”.

It should be guaranteed that every node only show “accessible” items in memory for the “visible” part of a dynamo graph, showing the user what happens/has happened. But it is not bulletproof, this is the problem with DAGs. Data does not always travel predictably.

The dynamo teams have made a life cycle collector for elements, which stores the items as a text string with a Revit elementId. But this comes with the issue of showing something that might not exist anymore!? if you use the option to delete elements, you will experience that you will get an error if you try to do something with those items afterward even though you can see them!? This is a weighted decision showing that normally will you not delete elements but work on them instead.

This is not the case with background-opened documents. I have decided that whenever you have made whatever you wanted AND you choose to close the document again, then I am pretty sure that you will not continue working on those documents. Therefore, it should be guaranteed that you could not see any document in those cases. But sadly you have seen that you could get a watch node to show the document. This is an error, you should never be able to see the document that you close.

How I can solve that someone builds graphs, where some parts are slowing the process just enough so other parts are being processed for the observer, is a “closing problem” for me. I don’t have access to the dynamo engine so I could ensure you never would be able to see the outcome from one node if another node where the elements are removed exists. Like the case is for the Dynamo team where elements are being deleted and somehow still exist.

However, if you stopped using the watch node as a data transfer node it would help enormously, watch nodes should only be used as an end node, nothing should be transferred out of a watch node in my opinion since this is one of the most dangerous nodes due to its “slowness”. Besides using watch nodes in a working environment is a complete waste of computational time.

If I at some point will have super much energy and no other things to do, I will try to see if I can code something into the “extension” library I have for my package, which is only available for the dynamo engine. I might have a chance to code something where I can set up “rules” for how a node should display its outcome!?

I will close this issue since it is not an error. It is more in the area of understanding how dynamo graphs and DAGs generally are working.

**Closed by erfajo** 2022-04-18 09:55 UTC
Labels: usage, solved

**Comment by Lazarica-t** [comment] 2022-04-18 13:58
I ran the graphs on the same computer.. I think it's more likely that you optimized the code for the nodes (from the old Orchid release that I was using until the present release). 
So basically I was seeing ghosts of the Revit families😆.

Thank you for the comprehensive explanations! 👍 It is more clear to me now

**Comment by erfajo** [comment] 2022-04-18 15:25
I have not done anything to the code for that function almost since it was created. I am sure it hasn't changed in the last two years.
Life circle on the other hand is on my mind from time to time, however, it is so difficult to predict anything when it comes to usage… therefore nearly no one does anything about it. If something fails, then just add an “await” node and it will in most cases be solved.

**Comment by Lazarica-t** [comment] 2022-04-19 09:48
hmm.. that is odd, Dynamo magic I guess.. 😅 
Thank you once again for all the support, really appreciate it 👍
