### ISSUE TITLE
FamilyParameter.SetValue - not working for many families in directory

### ISSUE THREAD

**Issue by cinkov** [erfajo/OrchidForDynamo#198] opened 2023-04-18 15:06 UTC
Revit: 22.1.21.13
Dynamo: 2.12.0.5650
Orchid: 212.4.0.5842

I am writing to report a problem related to the Orchid package that I would like to use for batch setting families parameters in a chosen directory.

The issue I am facing is that, despite finding a similar problem that was resolved earlier this year, the Orchid package is still not working correctly for me.
https://github.com/erfajo/OrchidForDynamo/issues/183
Specifically, I am trying to batch update families in a directory with multiple families, using one parameter with various different values. However, the package does not seem to be functioning as expected, and I have attached a JPEG image to illustrate the problem.

![InkedSetManyValues](https://user-images.githubusercontent.com/56067279/232819471-510774da-aa25-4cc7-bc34-76bd6231392b.jpg)
I have no idea why I don't see FamilyTypes - but the node is still working. I tried to connect data in the same way as in mentioned URL link.

**Comment by erfajo** [comment] 2023-04-19 05:10
while you send a "null" value into the parameter set value it will fail... so the problem is in the Family Type in document... can you add one family to this post?

**Comment by cinkov** [comment] 2023-04-19 07:36
I tested it on a few families but always it doesn't work correctly. I added one.

It looks weird that familytype.indocument returns 'null' and in the next node - I got the correct values for List.Count. If I run dynamo inside an open family (only for this one .rfa) - then it all looks like ok.
[Single-Flush.zip](https://github.com/erfajo/OrchidForDynamo/files/11270324/Single-Flush.zip)

**Comment by erfajo** [comment] 2023-04-19 10:04
hmmm... I cant reproduce your error, I get your types in the family.
![image](https://user-images.githubusercontent.com/2844374/233041111-804030f4-16eb-42bb-b97c-f2c2448f2176.png)
I will try to open more documents, but that should not change anything...

**Comment by cinkov** [comment] 2023-04-19 12:09
I used your part (only open families and family types) - and it works well!

I added next part, which sets values of parameters for all types and this is not working correctly. I have no idea what could be wrong.
[updated test file](https://github.com/erfajo/OrchidForDynamo/files/11272845/test2.dyn.txt)

**Comment by erfajo** [comment] 2023-04-19 14:02
I think I know where you go "wrong"... if you close you documents, then they are "removed" from memory. This means, when testing dont close your documents, and when everything is as expected, then start closing you documents.
However, you might run into problems while any "await" mechanism will have the "closing" problem as any "DAG" technology has.... and why we are working with  graphs and not scripting.
![image](https://user-images.githubusercontent.com/2844374/233099473-183b7129-06cd-4ad5-a13d-4e35f5143936.png)

**Closed** 2023-04-25 16:28 UTC
Labels: usage
