### ISSUE TITLE
Element.delete node

### ISSUE THREAD

**Issue by brane1012** [erfajo/OrchidForDynamo#128] opened 2021-09-16 08:33 UTC
Hi,

I am having a problem with your node element.delete. I am constantly getting error "Modifying  is forbidden because the document has no open transaction".

In earlier versions that node worked. I also attached my dynamo script.
[Test.zip](https://github.com/erfajo/OrchidForDynamo/files/7176190/Test.zip)

**Comment by erfajo** [comment] 2021-09-16 12:02
That sounds strange...
Could you upload a family which has elements to be deleted before reload?

besides, I have tweaked you GRAPH (not script), it included some errors.
[Test.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/7177491/Test.dyn.txt)

**Comment by brane1012** [comment] 2021-09-16 14:21
Hi,

I have attached rvt file with that family. It is pretty much the same with all families.
[Test.rvt.txt](https://github.com/erfajo/OrchidForDynamo/files/7178461/Test.rvt.txt)

**Comment by brane1012** [comment] 2021-09-16 15:14
And I also have a problem with your parameter rename node. I made a quick graph and I am always getting the same error:

Warning: Parameter.Rename operation failed. 
No parameter found by that name.

Is it something with the node or is it my graph? :S
[Test_upgrade.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/7178987/Test_upgrade.dyn.txt)

**Comment by erfajo** [comment] 2021-09-17 09:35
I have testet you graph, the first problem you mentioned...
As you can see it works as expected. However, the trick is to freeze the "delete node", then run the graph. unfreeze the delete node, and then run again. 
This means that the problem is not the "transaction". The node is coded correct. But it is a time issue or something else which come into play. I will try to see what can be done, but try if the trick could solve the issue here and now so you can finish your job.
![Test_2021-09-17_11-28-59](https://user-images.githubusercontent.com/2844374/133760636-f6d982f2-1fd4-4745-8d79-db023b4a4459.png)

I have not tested the other problem yet. (and in the future, please report only one problem in a thread otherwise will the answer become blurry )

**Comment by brane1012** [comment] 2021-09-17 09:36
Do I need to open new thread or will you be so kind to test it inside this thread?

**Comment by erfajo** [comment] 2021-09-17 14:02
I will handle the "extra" issue here asap...

**Comment by brane1012** [comment] 2021-09-17 14:33
Thanks for the support!

**Comment by HVCFOGEY34** [comment] 2022-01-26 15:14
I'm also having this issue but with the Document.BackgroundOpen and Element.Delete nodes. 

I had it twice now that the first time I open Revit and run my graph, the Element.Delete node didn't error. I can't reliable reproduce it though. Afterwards, If I try to close Revit and reopen it and run the graph immediately, it errors. It seems to only work first try (without freezing) if I haven't opened Revit in a while. Probably means nothing, but figured I'd mention it in case.

My hypothesis (that I don't know how to test) is could the Document.BackgroundOpen (or Family.Edit) node be outputting the list of documents before Revit had time to open them? In other words, Revit is still trying to open the documents by the time the document list is output and the Element.Delete node is computed.

I've tried to add a Thread.Pause node after the Document.BackgroundOpen node with a 10,000 millisecond (10 second) timer, but that seemed to just cause my graph to never finish, and I had to force close Revit and Dynamo.

**Comment by HVCFOGEY34** [comment] 2022-01-26 16:48
So I don't know if my hypothesis above is still right or not, but I made some progress and may have found a temporary solution. I put a Transaction.Start and End node linked together before the Element.Delete node, and it seems to run without needing to freeze the node prior to running the first time. I also had the same issue with the Document.Purge node, so I did the same there.
![image](https://user-images.githubusercontent.com/6226581/151199248-c6c51d39-010f-4dc5-a7e8-350cecbad2ae.png)

I have another Element.Delete node further down the line that I'm still having issues with. The Transaction.Start and End trick didn't exactly work for that one. For that node I originally had the document input set to use list levels @L1 and the element input as a list of elements (that is to be applied to each document). But to simplify the inputs, I changed it to not use list levels and instead first get the elements from the document using Element.ByID. See screenshots below (sorry for the mess of the nodes).

Was:
![image](https://user-images.githubusercontent.com/6226581/151205756-7eb87334-25a5-4230-973a-13e06b5af71e.png)

Now is:
![image](https://user-images.githubusercontent.com/6226581/151205587-3ed61a41-2426-4b9b-9b31-e942cc1ea480.png)

The first screenshot only ever worked for the first document. But with the process I describe below, I could get the second screenshot to work for all the documents, thought it is not a good work around by any means and very tedious.

The first time I run the graph, the node only works on the first document, and all the subsequent document's boolean output show nulls. If I freeze the node, run the graph again then unfreeze the node and run the graph one more time, it then works for the next (and only the next) document. I have to repeat that process for each subsequent document. 

Any advisement here would be nice. The graph I'm making is not a one time thing and will be reused often, so it would be nice for all of this to be automatic where I don't need to freeze nodes.

Thanks.

**Comment by erfajo** [comment] 2022-01-27 06:13
I am sure it is a transaction issue, that was what I changed with the last build and what I asked you to test... however you did not have the time to return me some minimal effort for being ahead.

Unfordenetly do I not have the time now, so you must tweak it with transaction nodes until I have the time for testing them.

In the meantime have I changed the transaction scenario all over the entire solution, but with a slightly different method as the last build. Wheater this will solve the problem or not can you verify when I release the next time (2 weeks). 

This time will no beta build be provided since I essentially am on my own for testing and verification of my functions. Meaning I need to be more certain of the coming-up build instead of moving something forward.

If there is an issue with the delete node after next release will I look into it again. 
Please start a new issue next time, I will close this issue.

**Closed by erfajo** 2022-01-27 06:13 UTC
Labels: bug
