### ISSUE TITLE
Parameter.GetValue wrong inputs

### ISSUE THREAD

**Issue by Crapai** [erfajo/OrchidForDynamo#56] opened 2019-12-17 15:43 UTC
Revit: 2020.2
Dynamo: 2.3
Orchid: 230.0.0.7288

I'm trying to get a script working that will help develop un-hosted families from face-based ones. I'm doing this by nesting the face-based version inside the un-hosted version.

The script will: 
Copy types
Copy family and shared parameters
Copy values and formulas

I'd also like it to associate the nested families parameters with the parent family.

I'm having issue getting the Parameter.GetValue node to work. I'm getting this error:

> Warning: Parameter.GetValue expects argument type(s) (Document, FamilyType[], string[]), but was called with (Autodesk.Revit.DB.Document, Revit.Elements.FamilyType[], string[]).

I'm using Orchid nodes to get the input for these and they appear to work for Parameter.Parameters and FamilyType.RevitFamily nodes. Is there a better way to get the correct inputs for this node? Shouldn't the same inputs work for all of them?

![AutodeskRevitDBxxx03](https://user-images.githubusercontent.com/50451766/71010407-c38c1e80-20b9-11ea-89f0-8773232799cb.PNG)

Here is the family and the script.

[Disconnect Dynamo Test.zip](https://github.com/erfajo/OrchidForDynamo/files/3974110/Disconnect.Dynamo.Test.zip)
[Revit Dev - Family - Copy nested parameters to host02.zip](https://github.com/erfajo/OrchidForDynamo/files/3974114/Revit.Dev.-.Family.-.Copy.nested.parameters.to.host02.zip)

**Comment by erfajo** [comment] 2019-12-17 19:27
First, I could not find any scripts... what do you mean when you write scripts?
I see you have sent a graph that consists of nodes connected by wires!? Script is a textual constitution like a Python script or DesignScript. I could not find any of that!?

However, I have an idea that you mean you have a problem with your graph since that is what you show on the image!? I am just guessing...

In that case, are you trying to mix pears and apples. The node says that the input must be an Orchid FamilyType, and you try to send a Dynamo FamilyType, that will never go.
The problem is what the Dynamo team calls FamilyType is a FamilySymbol in the Revit API, and the FamilySymbol class is used inside Project files to denote the types of a family. In a family document is a FamilyType the type you create, It is NOT the symbols loaded into a family! What makes this really difficult is, that a loaded family in a project with family types becomes Family Symbols.

Apparently was it not the intention from the dynamo team to support working inside FamilyDocuments, so they called it FamilyType because this is what users call them… but even many users is naming something wrongly, it doesn't become right! Maybe this is the same mistake as you call a graph a script!? It will not become a script just because many users don’t know what they are talking about.

That is why I had to do something.
So when you are working inside FamilyDocuments I have taken control over the types. This is why you can't feed a symbol to a FamilyType port. However, I am not consistent… sorry about that!
If you see the node Parameter.Associate, I write FamilyType, and that should be FamilySymbol… I will correct that so it will be fixed in the next version! The helping text for the port says “Nested family type in the familyDocument”, it should also say something like “Nested family symbol in the familyDocument”. I will also extend the node helping text, telling something about Symbols and Types…

If you want to know how to work with types and symbols, please see my sample collection

**Closed** 2020-01-02 20:36 UTC
Labels: solved, usage
