### ISSUE TITLE
SharedParameter.Add serious issue (0x00000007)

### ISSUE THREAD

**Issue by ClaudioBest** [erfajo/OrchidForDynamo#212] opened 2023-07-19 12:08 UTC
### Operating system
Windows 11 Pro

### Revit and Dynamo version
Revit: 2024.1.0
Dynamo Core: 2.18.1.5096
Dynamo Revit: 2.18.1.8943
Orchid: 218.0.0.5940

### What did you do? 
I wanted to add 2 shared parameters to my project:
![image](https://github.com/erfajo/OrchidForDynamo/assets/138873543/e92f74b1-cd8b-49dc-874f-756924a17be9)

### What did you expect to see?
In Dynamo it works:
![image](https://github.com/erfajo/OrchidForDynamo/assets/138873543/0cf3fe7d-c0e1-4f88-a67f-5534e0eac387)
After in Dynamo Player it works:
![image](https://github.com/erfajo/OrchidForDynamo/assets/138873543/8e44829e-5b8a-4ca8-b9d4-7e57d7dcbf81)
When I restart Revit and try the next project it should work now, without any warning.

### What did you see instead?
After restarting Revit and trying again only with Dynamo Player, it doesnt work:
![image](https://github.com/erfajo/OrchidForDynamo/assets/138873543/33ca3f71-9e61-45b8-8a1b-4a3c71f5b769)

**Comment by erfajo** [comment] 2023-07-19 13:44
I can see you must be from germany, and most likely be using a localized version of Revit/Dynamo...

Could you please send me the graph file? you can rename the file by adding ".txt" to the extension... 

Then I will try to see if this could be something!?

**Comment by ClaudioBest** [comment] 2023-07-21 15:25
Thanks for response, but i solved my problem by using another node from dynamo:
![image](https://github.com/erfajo/OrchidForDynamo/assets/138873543/950aee97-9b3f-4281-affe-1b3691b9403e)

**Comment by ClaudioBest** [comment] 2023-07-26 11:28
Ok, i was wrong, because the node from dynamo does not add the correct parameter. It creats a new one with same name but diffrent GUID. I cheked the GUID and its not the same from my shared parameter file. So i need your node, but your node shows me the warning I allready postet. What files do you need from me for your tests? the dynamo file and my shared parameter file and a revit file?

**Comment by erfajo** [comment] 2023-07-27 13:43
I had this issue half a year ago, and that was due to a localized version of Revit, however, not the German version, so that is kind of new... But I am sure I need to find out why or what is triggering that version and not the English version!?
But it is also time for my summer vacation, meaning it will take some weeks before I am on track again… I will come back when I am back after hiking in Sweden this year :-)

**Comment by ClaudioBest** [comment] 2023-07-27 14:39
ok, then i wish you a nice holiday and i hope to hear from you again soon. Maybe with a solution to the problem :-)

**Comment by erfajo** [comment] 2023-08-10 13:26
Hi,

I have tried to see where things could go wrong, and the only place seems to be if you only load the assemblies, and do not load the entire package.

To test that I have made some temporary changes in my code and built a beta version you can download. Please test that and return the error message… if the error is the same then you don’t open the entire package, and if you do then the error should be “0x00000007/x”

The beta build is named “OrchidForDynamo_218_BETA_5969.exe” and can be found under “Builds”.

**Comment by ClaudioBest** [comment] 2023-08-10 14:34
Hello, first thanks for your response and i hope your vacation was nice :) 
I did install your beta version:
![2023-08-10_16-24](https://github.com/erfajo/OrchidForDynamo/assets/138873543/806bf38d-21ae-4384-baba-95d9912e4103)
Did test my script and the same error did appear:
![2023-08-10_16-22](https://github.com/erfajo/OrchidForDynamo/assets/138873543/ecf74bdf-459a-4158-8361-db741250cce9)
What can i do now?

**Comment by ClaudioBest** [comment] 2023-08-10 15:58
Nice to hear that the holiday was successful. Such a break is certainly very good in today's fast-moving world and gives new energy.

Here are my Notifications (i already changed to english):
![2023-08-10_17-46_1](https://github.com/erfajo/OrchidForDynamo/assets/138873543/54c8443a-b3f8-445b-bad6-beb88d7340bf)

Here are my paths:
![2023-08-10_17-47](https://github.com/erfajo/OrchidForDynamo/assets/138873543/69241128-48c5-4c3e-8fce-2664950545de)
 
i switched to english and restartet Revit to test the dynamo player, but error again...

**Comment by erfajo** [comment] 2023-08-10 16:03
I see... this is strange, since the error says that the error is the missing IFC Exporter!?

Could you try to install this missing IFCexporter?
https://github.com/Autodesk/revit-ifc/releases

If this solves the error, then I have a problem, It should not be required to install the IFC exporter, but I do think most have this installed!? :-S

**Comment by ClaudioBest** [comment] 2023-08-10 16:18
I installed IFC Extension 24.1.1, but same error...
I only tested with the beta version.
Should i try the normal version?

**Comment by erfajo** [comment] 2023-08-10 16:22
And what about the errors? Is it only archilab that gives an error now? Could you move the folder with archilab to your desktop... And all other packages and test again?

**Comment by ClaudioBest** [comment] 2023-08-10 16:33
No notifications now from orchid, archilab still there.
I moved all folders expect orchid to desktop and check dynamo.
There is only orchid now:
![2023-08-10_18-31](https://github.com/erfajo/OrchidForDynamo/assets/138873543/a2181d95-6053-4f0e-93c8-b4ab94769cb5)
I tested again, but still error :(

**Comment by erfajo** [comment] 2023-08-11 12:41
I have to investigate if Dynamo Player does not use the ViewExtension, which could be meaningful since Dynamo does not start up as such, in Dynamo Player mode is it only running the graph!?
However, this means that I have to rewrite my code!? :-S
I will try to make a new beta for you…

**Comment by erfajo** [comment] 2023-08-11 13:00
When testing only running the graph, without opening it, in Dynamo Player, I also get the same error!
So The problem is Dynamo mPlayer not loading the ViewExtension as it does when opening Dynamo.... I really did not know that it didn’t do that, but now that I know it, I have to rewrite my code :-S

**Comment by erfajo** [comment] 2023-08-11 13:40
good thing is that it was easy to fix :-)
however, I am also testing some new nodes to be shipped, so I will make a new build later today, I will notice you :-)

**Comment by erfajo** [comment] 2023-08-11 15:32
I have just pushed a new version up... please test it again. 

I got it to work on my computer and I am convinced that this is also the case on your computer…

I am very glad that you took the time to write and that we in collaboration found the problem so I could fix it, I had never found this problem by myself, since I never test anything using only the Dynamo Player. I will nearly always have started Dynamo once before using the Dynamo Player…

…and you got the IFCexporter installed :-)

**Comment by ClaudioBest** [comment] 2023-08-14 06:42
Good morning, I just tested it and it finally works :) . Thanks alot.
Do you happen to know what I can do about this one error message from archilab?
![error](https://github.com/erfajo/OrchidForDynamo/assets/138873543/95fc6401-632b-4be1-b7e0-d33363f211c8)

**Comment by erfajo** [comment] 2023-08-14 06:46
Most of us who has the larger packages do create the individual version towards a specific version of Revit. 
Revit 2024.1 is rather new, and maybe has Konrad not updated his code to this specific version. Normally will things work for the next version but not if it is towards a lower version... I would just keep an eye on Archilab updates :-)

**Comment by erfajo** [comment] 2023-08-14 06:48
again, thanks for you report, it has helped me a lot :-)
I will close the issue as solved :-)

**Closed by erfajo** 2023-08-14 06:48 UTC
Labels: solved

**Comment by ClaudioBest** [comment] 2023-08-14 06:58
No problem, you helped me too, in germany we say "one hand washes the other" :)
And thanks for the advice with archilab, i´ll keep an eye on his homepage now for an update...
